name: Test_Move_Prover

on:
  repository_dispatch:
    types: [new_PR]

jobs:
  install_and_test_Move_Prover:

    runs-on: ubuntu-18.04
  
    steps:
    - name: Checkout libra
      uses: actions/checkout@v2
      with:
        path: "libra"
        repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }} # repo of the forked libra/libra
        ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR
    - name: Detect the changes in move-prover
      working-directory: ./libra
      env:
        BASE: ${{ github.event.client_payload.base_ref }}
      run: |
        git fetch origin
        git diff --name-only $BASE
        git diff --name-only $BASE | grep "language/move-prover"
    - name: Install Z3
      uses: pavpanchekha/setup-z3@v1.2
      with:
        version: "4.8.7"
    - name: Install .NET Core SDK and Boogie
      run: |
        wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install apt-transport-https
        sudo apt-get update
        sudo apt-get install dotnet-sdk-3.1
        dotnet tool install --global Boogie --version 2.5.7
    - name: Export the environment variables
      run: |
        echo "::set-env name=BOOGIE_EXE::/home/runner/.dotnet/tools/boogie"
        echo "::set-env name=Z3_EXE::`which z3`"
    - name: Test move-prover
      working-directory: ./libra/language/move-prover/bytecode-to-boogie
      timeout-minutes: 30 # normally, expected to be done within 10 mins.
      run: |
        set -o pipefail
        cargo test 2>&1 | tee cargo_test.log
    - name: Comment the error message if the test failed
      if: failure()
      uses: actions/github-script@0.5.0
      env:
        PULL_ID: ${{ github.event.client_payload.pull_id }}
      with:
        github-token: ${{secrets.MIRAI_BOT}}
        script: |
          const fs = require('fs');
          fs.readFile('libra/language/move-prover/bytecode-to-boogie/cargo_test.log', 'utf-8', async (err, data) => {
            if (err) {
              console.log("err:", err);
              console.log("`cargo test` has not launched. Perhaps, it was skipped because no changes under `language/move-prover` were found.");
              throw "No changes under `language/move-prover` were found.";
              return;
            }
            if (data) {
              lines = data.split('\n');
              data = lines.slice(lines.findIndex(line => line.includes('Running'))).join('\n');
              data = "[move-prover] `cargo test` failed with the following error message: \n```" + data + "```";    
              console.log(data);
            }
            await github.issues.createComment({
                owner: "libra",
                repo: "libra",
                issue_number: process.env.PULL_ID,
                body: data
              });
              throw "Move Prover test failed.";
          })
